export const productData = [
  {
    slug: '1',
    name: 'XENPAK-10GB-SR',
    price: '£55.00 GBP',
    image: '/images/1.jpg',
    description: 'Utilizing multimode fiber (MMF), it supports link lengths of up to 300 meters over OM3 fiber.',
  },
  {
    slug: '2',
    name: 'XENPAK-10GB-SR',
    price: '£60.00 GBP',
    image: '/images/2.jpg',
    description: 'Utilizing multimode fiber (MMF), it supports link lengths of up to 300 meters over OM3 fiber.',
  },
  { 
    slug: '3',
    name: 'XENPAK-10GB-SR',
    price: '£45.00 GBP',
    image: '/images/3.jpg',
    description: 'Utilizing multimode fiber (MMF), it supports link lengths of up to 300 meters over OM3 fiber.',
  },
  {
    slug: '4',
    name: 'X2-10GB-LX4',
    price: '£75.00 GBP',
    image: '/images/4.jpg',
    description: 'Cisco® GLC-TE Fyber Optix Compatible TAA 10/100/1000Base-T SFP Transceiver (Copper, 100m, RJ-45, -40 to 85C)',
  },
  {
    slug: 'sfp-9d',
    name: 'X2-10GB-LX4',
    price: '£85.00 GBP',
    image: '/images/5.jpg',
    description: 'It uses coarse wavelength-division multiplexing (CWDM) technology to transmit 10Gbps over standard multimode fiber (MMF) up to 300 meters, and over single-mode fiber (SMF) up to 10 kilometers, making it highly versatile for diverse network environments.',
  },
  {
    slug: '6',
    name: 'X2-10GB-LX4',
    price: '£95.00 GBP',
    image: '/images/6.jpg',
    description: 'It uses coarse wavelength-division multiplexing (CWDM) technology to transmit 10Gbps over standard multimode fiber (MMF) up to 300 meters, and over single-mode fiber (SMF) up to 10 kilometers, making it highly versatile for diverse network environments.',
  },
   {
    slug: '1',
    name: 'XENPAK-10GB-SR',
    price: '£55.00 GBP',
    image: '/images/1.jpg',
    description: 'Utilizing multimode fiber (MMF), it supports link lengths of up to 300 meters over OM3 fiber.',
  },
  {
    slug: '2',
    name: 'XENPAK-10GB-SR',
    price: '£60.00 GBP',
    image: '/images/2.jpg',
    description: 'Utilizing multimode fiber (MMF), it supports link lengths of up to 300 meters over OM3 fiber.',
  },
  { 
    slug: '3',
    name: 'XENPAK-10GB-SR',
    price: '£45.00 GBP',
    image: '/images/3.jpg',
    description: 'Utilizing multimode fiber (MMF), it supports link lengths of up to 300 meters over OM3 fiber.',
  },
  {
    slug: '4',
    name: 'X2-10GB-LX4',
    price: '£75.00 GBP',
    image: '/images/4.jpg',
    description: 'Cisco® GLC-TE Fyber Optix Compatible TAA 10/100/1000Base-T SFP Transceiver (Copper, 100m, RJ-45, -40 to 85C)',
  },
  {
    slug: 'sfp-9d',
    name: 'X2-10GB-LX4',
    price: '£85.00 GBP',
    image: '/images/5.jpg',
    description: 'It uses coarse wavelength-division multiplexing (CWDM) technology to transmit 10Gbps over standard multimode fiber (MMF) up to 300 meters, and over single-mode fiber (SMF) up to 10 kilometers, making it highly versatile for diverse network environments.',
  },
  {
    slug: '6',
    name: 'X2-10GB-LX4',
    price: '£95.00 GBP',
    image: '/images/6.jpg',
    description: 'It uses coarse wavelength-division multiplexing (CWDM) technology to transmit 10Gbps over standard multimode fiber (MMF) up to 300 meters, and over single-mode fiber (SMF) up to 10 kilometers, making it highly versatile for diverse network environments.',
  }
];
